#!/bin/bash
# A.R.E.S. — One-command installer for AlmaLinux 8 / 9 (and compatible RHEL clones)
#
# Usage (from inside the cloned repo):
#   sudo bash install-almalinux.sh
#
set -e

APP_DIR="/opt/ares"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN="\033[0;32m"; CYAN="\033[0;36m"; YELLOW="\033[1;33m"; RED="\033[0;31m"; NC="\033[0m"
info()    { echo -e "${CYAN}[•]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
die()     { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   A.R.E.S.  —  VPS Quick Installer       ║${NC}"
echo -e "${CYAN}║         AlmaLinux / RHEL edition          ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Root check ────────────────────────────────────────────────────────────────
[ "$EUID" -ne 0 ] && die "Please run as root: sudo bash install-almalinux.sh"

# ── Detect OS ─────────────────────────────────────────────────────────────────
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_ID="$ID"
  OS_VER="$VERSION_ID"
else
  die "Cannot detect OS."
fi

case "$OS_ID" in
  almalinux|rocky|rhel|centos|ol)
    info "OS: $OS_ID $OS_VER — supported"
    ;;
  *)
    warn "Detected OS: $OS_ID $OS_VER. This script is written for AlmaLinux/RHEL."
    warn "Proceeding anyway — some steps may fail."
    ;;
esac

# ── 1. Install Docker ─────────────────────────────────────────────────────────
info "Step 1/5 — Installing Docker..."

if command -v docker &>/dev/null; then
  success "Docker already installed: $(docker --version)"
else
  # Install prerequisites
  dnf install -y dnf-plugins-core curl openssl

  # Add the official Docker CE repo (uses the CentOS repo for all RHEL clones)
  dnf config-manager --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

  # Install Docker CE + Compose plugin
  dnf install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin

  systemctl enable --now docker
  success "Docker installed: $(docker --version)"
fi

# ── Configure Docker daemon DNS ───────────────────────────────────────────────
# Docker build containers resolve DNS through the daemon config.
# Without explicit DNS, builds fail with EAI_AGAIN on servers where iptables
# forwarding is restricted (cPanel/CSF, some VPS firewall policies).
python3 - <<'PYEOF'
import json, os
path = '/etc/docker/daemon.json'
try:
    with open(path) as f:
        cfg = json.load(f)
except (FileNotFoundError, ValueError):
    cfg = {}
if 'dns' not in cfg:
    cfg['dns'] = ['8.8.8.8', '1.1.1.1']
    os.makedirs('/etc/docker', exist_ok=True)
    with open(path, 'w') as f:
        json.dump(cfg, f, indent=2)
    print('Docker daemon: DNS set to 8.8.8.8, 1.1.1.1')
else:
    print('Docker daemon: DNS already configured')
PYEOF
systemctl restart docker
sleep 2

# ── 2. Get the source code ────────────────────────────────────────────────────
info "Step 2/5 — Setting up source code..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd || echo "")"

if [ -f "${SCRIPT_DIR}/docker-compose.yml" ] && [ -f "${SCRIPT_DIR}/Dockerfile" ]; then
  REPO_DIR="$SCRIPT_DIR"
  success "Using source at: $REPO_DIR"
else
  if [ -z "$GIT_REPO" ]; then
    echo ""
    echo "  Enter your git repository URL"
    echo "  (e.g. https://github.com/yourname/ares.git)"
    echo ""
    read -rp "  GIT_REPO: " GIT_REPO
    [ -z "$GIT_REPO" ] && die "No repository URL provided."
  fi

  GIT_BRANCH="${GIT_BRANCH:-main}"

  # Install git if missing
  command -v git &>/dev/null || dnf install -y git

  if [ -d "$APP_DIR/.git" ]; then
    info "Updating existing clone at $APP_DIR..."
    git -C "$APP_DIR" pull origin "$GIT_BRANCH"
  else
    info "Cloning $GIT_REPO (branch: $GIT_BRANCH) → $APP_DIR"
    git clone --depth=1 --branch "$GIT_BRANCH" "$GIT_REPO" "$APP_DIR"
  fi
  REPO_DIR="$APP_DIR"
  success "Source ready at: $REPO_DIR"
fi

# Link app dir if source is elsewhere
if [ "$REPO_DIR" != "$APP_DIR" ]; then
  mkdir -p "$(dirname "$APP_DIR")"
  ln -sfn "$REPO_DIR" "$APP_DIR" 2>/dev/null || true
fi

cd "$REPO_DIR"

# ── 3. Generate .env ──────────────────────────────────────────────────────────
info "Step 3/5 — Configuring environment..."

if [ -f "$REPO_DIR/.env" ]; then
  warn ".env already exists — skipping generation (delete it to reset)"
else
  DB_PASS=$(openssl rand -hex 32)
  APP_PORT="${PORT:-8080}"

  cat > "$REPO_DIR/.env" <<ENV
# A.R.E.S. production environment
# Generated by install-almalinux.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

POSTGRES_PASSWORD=${DB_PASS}
PORT=${APP_PORT}

# Git update settings (used by docker-update.sh)
GIT_REPO=${GIT_REPO:-}
GIT_BRANCH=${GIT_BRANCH:-main}
ENV

  chmod 600 "$REPO_DIR/.env"
  success ".env created with a generated database password"
fi

# Load env for display
set -a; source "$REPO_DIR/.env"; set +a

# ── 4. Open firewall port ─────────────────────────────────────────────────────
info "Step 4/5 — Configuring firewall..."

APP_PORT="${PORT:-8080}"

if command -v firewall-cmd &>/dev/null && systemctl is-active --quiet firewalld; then
  firewall-cmd --permanent --add-port="${APP_PORT}/tcp" &>/dev/null || true
  firewall-cmd --reload &>/dev/null || true
  success "Firewall: port ${APP_PORT} opened"
else
  warn "firewalld not active — skipping firewall rule (open port ${APP_PORT} manually if needed)"
fi

# ── 5. Build and start containers ─────────────────────────────────────────────
info "Step 5/6 — Building image (this takes a few minutes — full output shown)..."

# DOCKER_BUILDKIT=1 is required for RUN --network=host in the Dockerfile.
# Docker Compose v2 enables it by default, but we set it explicitly for safety.
export DOCKER_BUILDKIT=1

# Build separately so the full log is always visible.
# --no-cache ensures a clean build and avoids stale layer bugs.
docker compose -f "$REPO_DIR/docker-compose.yml" --env-file "$REPO_DIR/.env" \
  build --no-cache

info "Starting containers..."
docker compose -f "$REPO_DIR/docker-compose.yml" --env-file "$REPO_DIR/.env" \
  up -d --remove-orphans

success "Containers started."

# ── 6. Wait for health ────────────────────────────────────────────────────────
info "Step 6/6 — Waiting for app to become healthy..."

MAX_WAIT=90
ELAPSED=0
printf "    "
until curl -sf "http://localhost:${APP_PORT}/api/healthz" &>/dev/null; do
  if [ "$ELAPSED" -ge "$MAX_WAIT" ]; then
    echo ""
    warn "App did not become healthy within ${MAX_WAIT}s."
    warn "Check logs with:  docker compose logs -f app"
    break
  fi
  printf "."
  sleep 3
  ELAPSED=$((ELAPSED + 3))
done
echo ""
success "App is healthy."

# ── Done ──────────────────────────────────────────────────────────────────────
SERVER_IP=$(curl -sf https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Installation Complete!            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}App URL:${NC}       http://${SERVER_IP}:${APP_PORT}"
echo -e "  ${CYAN}Default login:${NC} admin@admin.local  /  Password%1"
echo ""
echo -e "  ${YELLOW}⚠  Change the admin password immediately after first login!${NC}"
echo ""
echo -e "  ${CYAN}Useful commands:${NC}"
echo "    docker compose logs -f app            # Live logs"
echo "    docker compose ps                     # Container status"
echo "    docker compose restart app            # Restart app"
echo "    sudo bash $REPO_DIR/docker-update.sh  # Update from git"
echo ""
echo -e "  ${CYAN}To enable HTTPS (recommended):${NC}"
echo "    dnf install -y nginx certbot python3-certbot-nginx"
echo "    certbot --nginx -d your-domain.com"
echo ""
echo -e "  ${CYAN}Env file:${NC} $REPO_DIR/.env"
echo ""
