#!/bin/bash
# A.R.E.S. — One-command installer for Rocky Linux 9
#
# Rocky Linux is a RHEL-compatible distribution.
# This script is functionally identical to install-almalinux.sh
# but detects and confirms Rocky Linux specifically.
#
# Usage (from inside the cloned repo):
#   sudo bash install-rocky.sh
#
set -e

APP_DIR="/opt/ares"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN="\033[0;32m"; CYAN="\033[0;36m"; YELLOW="\033[1;33m"; RED="\033[0;31m"; NC="\033[0m"
info()    { echo -e "${CYAN}[•]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
die()     { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   A.R.E.S.  —  VPS Quick Installer       ║${NC}"
echo -e "${CYAN}║           Rocky Linux 9 edition           ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Root check ────────────────────────────────────────────────────────────────
[ "$EUID" -ne 0 ] && die "Please run as root: sudo bash install-rocky.sh"

# ── Detect OS ─────────────────────────────────────────────────────────────────
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_ID="$ID"
  OS_VER="$VERSION_ID"
else
  die "Cannot detect OS."
fi

case "$OS_ID" in
  rocky)
    info "OS: Rocky Linux $OS_VER — supported"
    ;;
  almalinux|rhel|centos|ol)
    warn "Detected $OS_ID $OS_VER — this script targets Rocky Linux 9 but will work on compatible RHEL clones."
    ;;
  *)
    warn "Detected OS: $OS_ID $OS_VER. This script is written for Rocky Linux 9."
    warn "Proceeding anyway — some steps may fail."
    ;;
esac

# ── Require Rocky Linux 9 ─────────────────────────────────────────────────────
MAJOR_VER="${OS_VER%%.*}"
if [ "$OS_ID" = "rocky" ] && [ "$MAJOR_VER" -lt 9 ]; then
  warn "Rocky Linux $OS_VER detected. This script is optimised for Rocky 9."
  warn "Rocky 8 should also work but is not tested. Proceeding..."
fi

# ── 1. System preparation ─────────────────────────────────────────────────────
info "Step 1/6 — Preparing system..."

# Install essential tools
dnf install -y epel-release 2>/dev/null || true
dnf install -y dnf-plugins-core curl openssl git

# Disable SELinux enforcement for Docker compatibility (temporarily allow forwarding)
# We do NOT permanently disable SELinux — just permit httpd network connections
# so any local reverse proxy can reach Docker containers.
if command -v setsebool &>/dev/null; then
  setsebool -P httpd_can_network_connect 1 &>/dev/null || true
  info "SELinux: httpd_can_network_connect enabled (required for reverse proxy)"
fi

success "System prepared"

# ── 2. Install Docker ─────────────────────────────────────────────────────────
info "Step 2/6 — Installing Docker..."

if command -v docker &>/dev/null; then
  success "Docker already installed: $(docker --version)"
else
  # Add the official Docker CE repo for RHEL/CentOS
  dnf config-manager --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

  # Install Docker CE + Compose plugin
  dnf install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin

  systemctl enable --now docker
  success "Docker installed: $(docker --version)"
fi

# ── 3. Get the source code ────────────────────────────────────────────────────
info "Step 3/6 — Setting up source code..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd || echo "")"

if [ -f "${SCRIPT_DIR}/docker-compose.yml" ] && [ -f "${SCRIPT_DIR}/Dockerfile" ]; then
  REPO_DIR="$SCRIPT_DIR"
  success "Using source at: $REPO_DIR"
else
  if [ -z "$GIT_REPO" ]; then
    echo ""
    echo "  Enter your git repository URL"
    echo "  (e.g. https://github.com/yourname/ares.git)"
    echo ""
    read -rp "  GIT_REPO: " GIT_REPO
    [ -z "$GIT_REPO" ] && die "No repository URL provided."
  fi

  GIT_BRANCH="${GIT_BRANCH:-main}"

  if [ -d "$APP_DIR/.git" ]; then
    info "Updating existing clone at $APP_DIR..."
    git -C "$APP_DIR" pull origin "$GIT_BRANCH"
  else
    info "Cloning $GIT_REPO (branch: $GIT_BRANCH) → $APP_DIR"
    git clone --depth=1 --branch "$GIT_BRANCH" "$GIT_REPO" "$APP_DIR"
  fi
  REPO_DIR="$APP_DIR"
  success "Source ready at: $REPO_DIR"
fi

# Link app dir if source is elsewhere
if [ "$REPO_DIR" != "$APP_DIR" ]; then
  mkdir -p "$(dirname "$APP_DIR")"
  ln -sfn "$REPO_DIR" "$APP_DIR" 2>/dev/null || true
fi

cd "$REPO_DIR"

# ── 4. Generate .env ──────────────────────────────────────────────────────────
info "Step 4/6 — Configuring environment..."

if [ -f "$REPO_DIR/.env" ]; then
  warn ".env already exists — skipping generation (delete it to reset)"
else
  DB_PASS=$(openssl rand -hex 32)
  APP_PORT="${PORT:-8080}"

  cat > "$REPO_DIR/.env" <<ENV
# A.R.E.S. production environment
# Generated by install-rocky.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

POSTGRES_PASSWORD=${DB_PASS}
PORT=${APP_PORT}

# Git update settings (used by docker-update.sh)
GIT_REPO=${GIT_REPO:-}
GIT_BRANCH=${GIT_BRANCH:-main}
ENV

  chmod 600 "$REPO_DIR/.env"
  success ".env created with a generated database password"
fi

# Load env for display
set -a; source "$REPO_DIR/.env"; set +a
APP_PORT="${PORT:-8080}"

# ── 5. Open firewall port ─────────────────────────────────────────────────────
info "Step 5/6 — Configuring firewall..."

if command -v firewall-cmd &>/dev/null && systemctl is-active --quiet firewalld; then
  firewall-cmd --permanent --add-port="${APP_PORT}/tcp" &>/dev/null || true
  firewall-cmd --permanent --add-service=http  &>/dev/null || true
  firewall-cmd --permanent --add-service=https &>/dev/null || true
  firewall-cmd --reload &>/dev/null || true
  success "firewalld: port ${APP_PORT} + HTTP/HTTPS opened"
elif command -v csf &>/dev/null; then
  csf -a "tcp ${APP_PORT}" 2>/dev/null || true
  csf -r &>/dev/null || true
  success "CSF: port ${APP_PORT} opened"
else
  warn "No recognised firewall found — open port ${APP_PORT} manually if needed"
fi

# ── 6. Build and start containers ─────────────────────────────────────────────
info "Step 6/7 — Building image (this takes a few minutes — full output shown)..."

# Build separately so the full log is always visible.
# --no-cache ensures a clean build and avoids stale layer bugs.
docker compose -f "$REPO_DIR/docker-compose.yml" --env-file "$REPO_DIR/.env" \
  build --no-cache

info "Starting containers..."
docker compose -f "$REPO_DIR/docker-compose.yml" --env-file "$REPO_DIR/.env" \
  up -d --remove-orphans

success "Containers started."

# ── 7. Wait for health ────────────────────────────────────────────────────────
info "Step 7/7 — Waiting for app to become healthy..."

MAX_WAIT=90
ELAPSED=0
printf "    "
until curl -sf "http://localhost:${APP_PORT}/api/healthz" &>/dev/null; do
  if [ "$ELAPSED" -ge "$MAX_WAIT" ]; then
    echo ""
    warn "App did not become healthy within ${MAX_WAIT}s."
    warn "Check logs with:  docker compose logs -f app"
    break
  fi
  printf "."
  sleep 3
  ELAPSED=$((ELAPSED + 3))
done
echo ""
success "App is healthy."

# ── Done ──────────────────────────────────────────────────────────────────────
SERVER_IP=$(curl -sf https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Installation Complete!            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}App URL:${NC}       http://${SERVER_IP}:${APP_PORT}"
echo -e "  ${CYAN}Default login:${NC} admin@admin.local  /  Password%1"
echo ""
echo -e "  ${YELLOW}⚠  Change the admin password immediately after first login!${NC}"
echo ""
echo -e "  ${CYAN}Publishing (making it accessible at a domain):${NC}"
echo "    1. Point your domain's A record → ${SERVER_IP}"
echo "    2. Set up Nginx reverse proxy  (see INSTALL.md)"
echo "    3. Issue a free SSL certificate:"
echo "       dnf install -y certbot python3-certbot-nginx"
echo "       certbot --nginx -d your-domain.com"
echo ""
echo -e "  ${CYAN}Useful commands:${NC}"
echo "    docker compose logs -f app            # Live logs"
echo "    docker compose ps                     # Container status"
echo "    docker compose restart app            # Restart app"
echo "    sudo bash $REPO_DIR/docker-update.sh  # Update from git"
echo ""
echo -e "  ${CYAN}Env file:${NC} $REPO_DIR/.env"
echo ""
